openapi: 3.1.0
info:
  title: Link shortener docs
  description: Documents for golang link shortener.
  version: 1.0.0
servers:
  - url: http://localhost:8005
  - url: http://localhost:8005

paths:
  /url/create:
    post:
      summary: Create a short url.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                original_url:
                  type: string
                custom_url:
                  type: string
                title:
                  type: string
                expire_date:
                  type: string
              example:
                original_url: https://zoodex.ir/
                title: Zoodex home page
                expire_date: 2024-03-05 12:34:16
      responses:
        "200":
          description: Short url has been created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: ?string
                  original_url:
                    type: string
                  short_link:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  deleted_at:
                    type: ?string
                  expire_date:
                    type: ?string
                  status:
                    type: number
                example:
                  id: "65ebe86993c37cf386c9804b"
                  title: "test"
                  short_link: "kGrAS"
                  original_url: "https://admin.zoodex.ir"
                  created_at: "2024-03-09 08:11:13"
                  updated_at: "2024-03-09 08:11:13"
                  deleted_at: ""
                  expire_date: "2024-03-10 14:48:09"
                  status: 1

        "422":
          description: Wrong input.
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "Wrong input."


  /url/delete:
    post:
      summary: Delete a url (Deactivate)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              example:
                id: "65ebe86993c37cf386c9804b"
      responses:
        "200":
          description: Url has been deleted.
          content:
            application/json:
              schema:
                type: object
                example:
                  success: "ok"
                  message: "Url has been deleted."
        "404":
          description: Url not found.
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "Url not found."
        "422":
          description: Wrong input.
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "Invalid input."
